# This workflow will deploy project on curseforge
# Currently does not work :(
# There is no GIT_COMMIT env variable in github actions (needed in build.gradle)

name: Gradle deploy

on:
  repository_dispatch:
    types: deploy

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Decrypt secrets.json
        run: |
          mkdir $HOME/secrets
          gpg --quiet --batch --yes --decrypt --passphrase "$SECRET_PASSPHRASE" \
          --output $HOME/secrets/secrets.json secrets.json.gpg
        env:
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble project
        run: ./gradlew assemble

      - name: Build with Gradle
        run: ./gradlew build

      - name: Deploy on curseforge
        run: ./gradlew curseforge -PsecretFile="$HOME/secrets/secrets.json"
